spring.application.name=Bank manage system with java,springboot

spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=bankuser
spring.datasource.password=Harsha@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


server.port=8080